### ISSUE TITLE
Develop a color layer for scalar values (eg temperature)

### ISSUE THREAD

**Issue by claustres** [weacast/weacast-app#12]
WIP, working but not optimized, see https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/issues/7

**Comment by claustres** [comment]
Maybe better to switch to WebGL rendering, e.g. should be simple to draw a grid overlay with https://github.com/manubb/Leaflet.PixiOverlay.

**Comment by claustres** [comment]
We encounter the same issue than https://github.com/IHCantabria/Leaflet.CanvasLayer.Field/issues/8 with GFS, the layer should be updated to manage longitude wrapping when input data grid are specified in range [0, 360] and not [-180, 180].

Maybe we should enhance our Grid class to manage the formatting of input data in the same reference system. To avoid any artifacts this has to be taken into account when interpolating.

**Comment by cnouguier** [comment]
It also seems that in some cases we exceed the WebGL vertex buffer size limit. For now we create one mesh, we can subdivide the grid in order to produce multiple mesh.
