### ISSUE TITLE
[HPM] Client disconnected

### ISSUE THREAD

**Issue by chenwei19940207** [weacast/weacast-app#67]
Hi @claustres , I am trying running dev from source code with weacast-api and weacast-app. However, the front end won't turn in to the state of logged in but stuck at the home page(http://localhost:8080/#/home), while the terminal gives me  the following info when I log in the app with default user name and password.

`[HPM] GET /apiws/?EIO=4&transport=websocket -> http://localhost:8081
[HPM] Upgrading to WebSocket
[HPM] Client disconnected
`

Could you please give me any hint or quick answer to log in the app properly? Thank you!

I'm using windows 11 with Nodejs 16.10.0 and npm 7.24.0

**Comment by claustres** [comment]
Is there any error message in the developer console of the browser ? Could it be related to https://github.com/weacast/weacast/issues/16 ? Which version of the api/demo app are you using ?

**Comment by chenwei19940207** [comment]
@claustres Console gives me the following when loaded. And nothing wrong after clicking the OK button of Sign in pop up.
`feathers.js?82fd:228 
       Uncaught (in promise) NotAuthenticated: No accessToken found in storage
    at eval (eval at <anonymous> (http://localhost:8080/js/app.js:4757:1), <anonymous>:228:19)`

I cloned the master of https://github.com/weacast/weacast-api.git and this https://github.com/weacast/weacast-app.git

Btw the font end terminal stuck at [HPM] Upgrading to WebSocket after clicking OK button.

**Comment by claustres** [comment]
As discussed in the mentioned issue the master branch of the demo app is not compatible with the API module anymore because we are currently migrating to a new version of Feathers. Please clone the latest tag of the demo app instead (https://github.com/weacast/weacast-app/tree/v1.3.0).

The master branch is usually reserved for development, for predictable results it is always better to rely on releases (either docker images or repo tags).

**Comment by chenwei19940207** [comment]
@claustres God I just figured out what do you mean by repo tags since I'm totally new of Github. I've tried docker images but the docker container is supposed not to modify right? Thanks  you very much for the patient answer and I'm gonna close this issue.

**Comment by claustres** [comment]
Docker images cannot be modified directly and are useful to test/deploy a weacast instance as is. If you'd like to develop weacast modules then yes you need to use the github repositories.

**Comment by chenwei19940207** [comment]
@claustres Trying to add features for adding customized wms service.

**Comment by claustres** [comment]
Do not hesitate to explain what you'd like to do, we might be able to give some insights. For instance you might be interested by https://kalisio.github.io/kano/, it can be connected to the Weacast API and WMTS/TMS/WFS/WMS(-timed) services as well.

**Comment by chenwei19940207** [comment]
@claustres  I'm from wind power industry and I find weacast is really helpful for monitoring wind turbine by using the probe module to extract and visualize data dynamically from GFS or any other weather model. For example icing of wind turbine will lead to shutdown and power lost. An experienced technician can easily determine and predict the icing condition by judging from future precipitation, wind speed, humidity and many other factors. Since our turbine geodata is managed by WMS/WMS service, I find it really important to add the feature to support  these online services. But I'll look into Kano to see if it would help. Thanks!

**Comment by claustres** [comment]
Pretty interesting @chenwei19940207, my company develops a product, which integrates Weacast and Kano, to provide situational awareness, I think you are talking about something like https://aktnmap.com/gofurther/alert.html. If you are interested by such services contact me privately on LinkedIn and we can have a conversation about your needs and how we can help.
